# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3310953cca1241496771620a0e75969f"
name = "Wishlist"
handle = "wishlist-486"
application_url = "https://speak-coastal-menus-extra.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "coffaia.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://speak-coastal-menus-extra.trycloudflare.com/auth/callback",
  "https://speak-coastal-menus-extra.trycloudflare.com/auth/shopify/callback",
  "https://speak-coastal-menus-extra.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
