# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13f3c2657b60a8e62026079ead8a0751"
name = "wishlist"
handle = "wishlist-533"
application_url = "https://wisdom-organize-apparatus-cologne.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appcarto.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://wisdom-organize-apparatus-cologne.trycloudflare.com/auth/callback",
  "https://wisdom-organize-apparatus-cologne.trycloudflare.com/auth/shopify/callback",
  "https://wisdom-organize-apparatus-cologne.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
